### ISSUE TITLE
TypeError: expected bytes, str found

### ISSUE THREAD

**Issue by holdsworth** [supsi-dacd-isaac/influxdb-to-hdf5#1]
user@machine:~/influxdb-to-hdf5$ python3.6 bridge.py -c conf/myconfig.json 
2018-08-15 10:44:52,038::INFO::<module>::Starting program
2018-08-15 10:44:52,038::INFO::<module>::InfluxDB connection -> socket=localhost:8086; user=myuser, db=mydb
2018-08-15 10:44:52,038::INFO::<module>::Connection OK
2018-08-15 10:44:52,039::INFO::<module>::Query: **MY_QUERY**
Traceback (most recent call last):
  File "bridge.py", line 162, in <module>
    hdf5_file_obj = h5py.h5f.create(config['hdf5_file'])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 82, in h5py.h5f.create
TypeError: expected bytes, str found

Running on Ubuntu 16.04 with latest InfluxDB

**Comment by dstreppa** [comment]
The problem is that the current version does not work with python3. I've updated the typo in README file.

**Comment by holdsworth** [comment]
I see, thanks for the response.

On Aug 20, 2018 9:28 AM, "Davide Strepparava" <notifications@github.com>
wrote:

The problem is that the current version does not work with python3

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/supsi-dacd-isaac/influxdb-to-hdf5/issues/1#issuecomment-414210384>,
or mute the thread
